"""Domain-specific tools for Studio Copilot.

Each tool has two pieces:
1. A Python function that performs the real work.
2. A JSON schema in TOOLS that tells Gemini when and how to call it.
"""

import json
import re
import math
import os
import time
import requests
from pathlib import Path
import librosa
import numpy as np

from project_state import UPDATE_PROJECT_STATE_TOOL, guarded_update_project_state, update_project_state

AUDIO_UPLOAD_DIR = Path(
    os.getenv("AUDIO_UPLOAD_DIR", "/tmp/studio_copilot_audio")
)

AUDIO_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

SPECTROGRAM_CACHE_DIR = Path(
    os.getenv("SPECTROGRAM_CACHE_DIR", "/tmp/studio_copilot_spectrograms")
)

SPECTROGRAM_CACHE_DIR.mkdir(parents=True, exist_ok=True)

# Must match the IDs generated by /upload-audio: uuid4().hex + extension.
AUDIO_FILE_ID_PATTERN = re.compile(r"[0-9a-f]{32}\.(wav|mp3|flac|ogg)")

# Requested ranges may overshoot the decoded duration by this much (rounding,
# decoder padding) before they are treated as out of range.
RANGE_END_TOLERANCE_SECONDS = 1.0

_AUDIO_DURATION_CACHE: dict[str, float] = {}


def resolve_uploaded_audio(audio_file_id: str) -> Path:
    """Return the path of an uploaded audio file.

    Raises ValueError for a malformed ID and FileNotFoundError when the file
    is not present in the upload directory.
    """
    if not isinstance(audio_file_id, str) or not AUDIO_FILE_ID_PATTERN.fullmatch(audio_file_id):
        raise ValueError("Invalid audio file ID.")

    file_path = AUDIO_UPLOAD_DIR / audio_file_id

    if not file_path.is_file():
        raise FileNotFoundError("The uploaded audio file could not be found.")

    return file_path


def get_audio_duration(file_path: Path) -> float:
    """Duration in seconds of an uploaded audio file, cached per file."""
    key = file_path.name

    if key not in _AUDIO_DURATION_CACHE:
        _AUDIO_DURATION_CACHE[key] = float(librosa.get_duration(path=str(file_path)))

    return _AUDIO_DURATION_CACHE[key]

# Pitch classes are represented as semitone offsets from C.
NOTE_TO_PITCH_CLASS = {
    "C": 0,
    "B#": 0,
    "C#": 1,
    "DB": 1,
    "D": 2,
    "D#": 3,
    "EB": 3,
    "E": 4,
    "FB": 4,
    "E#": 5,
    "F": 5,
    "F#": 6,
    "GB": 6,
    "G": 7,
    "G#": 8,
    "AB": 8,
    "A": 9,
    "A#": 10,
    "BB": 10,
    "B": 11,
    "CB": 11,
}

PITCH_CLASS_TO_NAME = {
    0: "C",
    1: "C#/Db",
    2: "D",
    3: "D#/Eb",
    4: "E",
    5: "F",
    6: "F#/Gb",
    7: "G",
    8: "G#/Ab",
    9: "A",
    10: "A#/Bb",
    11: "B",
}
KEY_NAMES = [
    "C",
    "C#/Db",
    "D",
    "D#/Eb",
    "E",
    "F",
    "F#/Gb",
    "G",
    "G#/Ab",
    "A",
    "A#/Bb",
    "B",
]

# Krumhansl-Schmuckler major/minor pitch-class profiles.
MAJOR_KEY_PROFILE = np.array([
    6.35, 2.23, 3.48, 2.33, 4.38, 4.09,
    2.52, 5.19, 2.39, 3.66, 2.29, 2.88,
])

MINOR_KEY_PROFILE = np.array([
    6.33, 2.68, 3.52, 5.38, 2.60, 3.53,
    2.54, 4.75, 3.98, 2.69, 3.34, 3.17,
])


def _parse_key(key: str) -> dict:
    """Parse a practical key label such as 'Dm', 'D minor', or 'F# major'."""
    if not isinstance(key, str) or not key.strip():
        raise ValueError("Key must be a non-empty string, e.g. 'D minor' or 'F# major'.")

    cleaned = key.strip().replace("♯", "#").replace("♭", "b")
    compact = re.sub(r"\s+", "", cleaned)

    match = re.fullmatch(r"([A-Ga-g])([#b]?)(major|minor|maj|min|m)?", compact, flags=re.IGNORECASE)
    if not match:
        raise ValueError(
            f"Could not understand key '{key}'. Use a format like 'D minor', 'Dm', 'F# major', or 'Gb'."
        )

    note, accidental, quality = match.groups()
    note_name = (note.upper() + accidental).upper()
    if note_name not in NOTE_TO_PITCH_CLASS:
        raise ValueError(f"Unsupported note name in key '{key}'.")

    quality_norm = (quality or "").lower()
    if quality_norm in {"minor", "min", "m"}:
        mode = "minor"
    elif quality_norm in {"major", "maj", ""}:
        mode = "major" if quality_norm else "unspecified"
    else:
        mode = "unspecified"

    pitch_class = NOTE_TO_PITCH_CLASS[note_name]
    return {
        "input": key,
        "root": PITCH_CLASS_TO_NAME[pitch_class],
        "pitch_class": pitch_class,
        "mode": mode,
    }


def _shortest_pitch_shift(source_pc: int, target_pc: int) -> tuple[int, int]:
    """Return the smallest signed semitone shift and an octave-equivalent alternative."""
    upward = (target_pc - source_pc) % 12

    # Prefer the smallest absolute motion. For a tritone, prefer +6 rather than -6.
    if upward <= 6:
        recommended = upward
    else:
        recommended = upward - 12

    if recommended > 0:
        alternate = recommended - 12
    elif recommended < 0:
        alternate = recommended + 12
    else:
        alternate = 12

    return recommended, alternate


def transform_sample(
    source_bpm: float,
    target_bpm: float,
    source_key: str | None = None,
    target_key: str | None = None,
    bars: int | None = None,
    beats_per_bar: int = 4,
) -> str:
    """Calculate tempo and pitch transformations needed to adapt a sample to a new track.

    The function returns deterministic production math. Gemini should use the result to
    explain the workflow and offer creative production advice.
    """
    try:
        source_bpm = float(source_bpm)
        target_bpm = float(target_bpm)
    except (TypeError, ValueError):
        return json.dumps({"error": "source_bpm and target_bpm must both be numbers."})

    if source_bpm <= 0 or target_bpm <= 0:
        return json.dumps({"error": "BPM values must be greater than 0."})
    if source_bpm > 400 or target_bpm > 400:
        return json.dumps({"error": "BPM values above 400 are outside this tool's supported range."})

    if bars is not None:
        if isinstance(bars, bool) or not isinstance(bars, int) or bars <= 0:
            return json.dumps({"error": "bars must be a positive whole number when provided."})

    if isinstance(beats_per_bar, bool) or not isinstance(beats_per_bar, int) or beats_per_bar <= 0:
        return json.dumps({"error": "beats_per_bar must be a positive whole number."})

    playback_speed_ratio = target_bpm / source_bpm
    duration_ratio = source_bpm / target_bpm
    tempo_change_pct = (playback_speed_ratio - 1.0) * 100.0

    result = {
        "source_bpm": round(source_bpm, 3),
        "target_bpm": round(target_bpm, 3),
        "tempo_change_percent": round(tempo_change_pct, 2),
        "playback_speed_ratio": round(playback_speed_ratio, 5),
        "target_duration_ratio": round(duration_ratio, 5),
        "time_stretch_instruction": (
            f"Make the sample {duration_ratio * 100:.2f}% of its original duration "
            f"to move from {source_bpm:g} BPM to {target_bpm:g} BPM while preserving bar count."
        ),
    }

    if bars is not None:
        source_duration = bars * beats_per_bar * 60.0 / source_bpm
        target_duration = bars * beats_per_bar * 60.0 / target_bpm
        result["loop"] = {
            "bars": bars,
            "beats_per_bar": beats_per_bar,
            "source_duration_seconds": round(source_duration, 3),
            "target_duration_seconds": round(target_duration, 3),
        }

    if source_key is not None or target_key is not None:
        if not source_key or not target_key:
            return json.dumps({
                "error": "To calculate pitch shifting, provide both source_key and target_key."
            })

        try:
            source = _parse_key(source_key)
            target = _parse_key(target_key)
        except ValueError as e:
            return json.dumps({"error": str(e)})

        recommended, alternate = _shortest_pitch_shift(source["pitch_class"], target["pitch_class"])

        mode_note = None
        if (
            source["mode"] != "unspecified"
            and target["mode"] != "unspecified"
            and source["mode"] != target["mode"]
        ):
            mode_note = (
                f"The roots can be aligned by pitch shifting, but the source is {source['mode']} "
                f"and the target is {target['mode']}. Pitch shifting alone will not change the "
                "sample's major/minor harmonic quality."
            )

        result["pitch"] = {
            "source_key": source_key,
            "target_key": target_key,
            "recommended_shift_semitones": recommended,
            "octave_equivalent_alternative_semitones": alternate,
            "direction": "up" if recommended > 0 else "down" if recommended < 0 else "none",
            "mode_warning": mode_note,
        }

    return json.dumps(result)
def _format_timestamp(seconds: float) -> str:
    """Format seconds as M:SS."""
    seconds = max(0, round(seconds))
    minutes, secs = divmod(seconds, 60)
    return f"{minutes}:{secs:02d}"


def _section_weight(section_name: str) -> float:
    """
    Relative amount of arrangement space usually given to common song sections.

    These are not rigid musical rules. They are only used to distribute the
    requested total duration across sections while keeping everything aligned
    to 4-bar blocks.
    """
    name = section_name.lower().strip().replace("_", " ").replace("-", " ")

    if "intro" in name:
        return 0.75
    if "outro" in name:
        return 0.75
    if "pre chorus" in name or "prechorus" in name:
        return 0.75
    if "build" in name:
        return 0.75
    if "chorus" in name:
        return 1.25
    if "drop" in name:
        return 1.50
    if "verse" in name:
        return 1.25
    if "breakdown" in name:
        return 1.00
    if "bridge" in name:
        return 1.00
    if "instrumental" in name:
        return 1.00

    return 1.00


def build_arrangement(
    bpm: float,
    target_duration_seconds: float,
    sections: list[str],
    time_signature: str = "4/4",
) -> str:
    """
    Build a bar-accurate song arrangement from an ordered section list.

    The resulting arrangement is aligned to four-bar blocks so that section
    boundaries remain musically practical.
    """
    try:
        bpm = float(bpm)
        target_duration_seconds = float(target_duration_seconds)

        if bpm <= 0:
            return json.dumps({
                "error": "BPM must be greater than zero.",
                "action": "Provide a positive BPM such as 120 or 128."
            })

        if target_duration_seconds <= 0:
            return json.dumps({
                "error": "Target duration must be greater than zero.",
                "action": "Provide the desired track length in seconds."
            })

        if not sections or not isinstance(sections, list):
            return json.dumps({
                "error": "At least one song section is required.",
                "action": (
                    "Provide an ordered section list such as "
                    "['intro', 'verse', 'chorus', 'verse', 'chorus', 'outro']."
                )
            })

        sections = [
            str(section).strip()
            for section in sections
            if str(section).strip()
        ]

        if not sections:
            return json.dumps({
                "error": "No valid section names were provided.",
                "action": "Provide at least one named song section."
            })

        # Keep the first version intentionally unambiguous.
        try:
            numerator, denominator = [
                int(x) for x in time_signature.split("/")
            ]
        except Exception:
            return json.dumps({
                "error": f"Invalid time signature: {time_signature}",
                "action": "Use a value such as '4/4' or '3/4'."
            })

        if numerator <= 0 or denominator != 4:
            return json.dumps({
                "error": (
                    f"Time signature {time_signature} is not currently supported."
                ),
                "action": (
                    "This version supports quarter-note based meters such as "
                    "4/4 or 3/4. Use 4/4 unless your track requires another meter."
                )
            })

        seconds_per_beat = 60.0 / bpm
        seconds_per_bar = numerator * seconds_per_beat

        raw_target_bars = target_duration_seconds / seconds_per_bar

        # Song sections are arranged in four-bar blocks.
        target_four_bar_units = max(
            len(sections),
            round(raw_target_bars / 4)
        )

        total_bars = target_four_bar_units * 4

        # Every requested section gets at least four bars.
        units_per_section = [1] * len(sections)
        remaining_units = target_four_bar_units - len(sections)

        if remaining_units > 0:
            weights = [_section_weight(section) for section in sections]
            weight_sum = sum(weights)

            exact_extra_units = [
                remaining_units * weight / weight_sum
                for weight in weights
            ]

            floor_units = [
                math.floor(value)
                for value in exact_extra_units
            ]

            for i, extra in enumerate(floor_units):
                units_per_section[i] += extra

            leftover = remaining_units - sum(floor_units)

            # Largest-remainder allocation keeps the total exact.
            fractional_order = sorted(
                range(len(sections)),
                key=lambda i: exact_extra_units[i] - floor_units[i],
                reverse=True,
            )

            for i in fractional_order[:leftover]:
                units_per_section[i] += 1

        arrangement = []
        current_bar = 1

        for section_name, units in zip(sections, units_per_section):
            bar_count = units * 4

            start_bar = current_bar
            end_bar = current_bar + bar_count - 1

            start_seconds = (start_bar - 1) * seconds_per_bar
            end_seconds = end_bar * seconds_per_bar

            arrangement.append({
                "section": section_name,
                "start_bar": start_bar,
                "end_bar": end_bar,
                "bars": bar_count,
                "start_time": _format_timestamp(start_seconds),
                "end_time": _format_timestamp(end_seconds),
                "start_seconds": round(start_seconds, 2),
                "end_seconds": round(end_seconds, 2),
            })

            current_bar = end_bar + 1

        actual_duration_seconds = total_bars * seconds_per_bar
        duration_difference = (
            actual_duration_seconds - target_duration_seconds
        )

        result = {
            "bpm": bpm,
            "time_signature": time_signature,
            "seconds_per_bar": round(seconds_per_bar, 3),

            "requested_duration_seconds": round(
                target_duration_seconds, 2
            ),
            "requested_duration": _format_timestamp(
                target_duration_seconds
            ),

            "actual_duration_seconds": round(
                actual_duration_seconds, 2
            ),
            "actual_duration": _format_timestamp(
                actual_duration_seconds
            ),

            "duration_difference_seconds": round(
                duration_difference, 2
            ),

            "total_bars": total_bars,
            "arrangement": arrangement,

            "note": (
                "Section boundaries are aligned to four-bar blocks. "
                "The actual duration may differ slightly from the requested "
                "duration so that the arrangement remains musically practical."
            ),
        }

        return json.dumps(result)

    except Exception as exc:
        return json.dumps({
            "error": "Could not build the arrangement.",
            "details": str(exc),
            "action": (
                "Check that BPM and duration are numeric and that sections "
                "is an ordered list of song section names."
            )
        })

MUSICBRAINZ_API_URL = "https://musicbrainz.org/ws/2/recording/"
_LAST_MUSICBRAINZ_REQUEST = 0.0

# MusicBrainz asks ordinary clients to stay around one request per second.
MUSICBRAINZ_MIN_INTERVAL_SECONDS = 1.05
MUSICBRAINZ_MAX_ATTEMPTS = 3
MUSICBRAINZ_BACKOFF_SECONDS = 1.0
MUSICBRAINZ_RETRYABLE_STATUS = {429, 500, 502, 503, 504}

# (normalized title, normalized artist) -> successful lookup result JSON.
_REFERENCE_LOOKUP_CACHE: dict[tuple[str, str], str] = {}
REFERENCE_LOOKUP_CACHE_SIZE = 128


def _musicbrainz_get(params: dict, headers: dict):
    """GET with request spacing and bounded retries for transient failures.

    Returns (response, None) on an HTTP 2xx, otherwise (None, error_dict).
    """
    global _LAST_MUSICBRAINZ_REQUEST

    error = None

    for attempt in range(1, MUSICBRAINZ_MAX_ATTEMPTS + 1):
        if attempt > 1:
            time.sleep(MUSICBRAINZ_BACKOFF_SECONDS * 2 ** (attempt - 2))

        elapsed = time.monotonic() - _LAST_MUSICBRAINZ_REQUEST
        if elapsed < MUSICBRAINZ_MIN_INTERVAL_SECONDS:
            time.sleep(MUSICBRAINZ_MIN_INTERVAL_SECONDS - elapsed)

        try:
            response = requests.get(
                MUSICBRAINZ_API_URL,
                params=params,
                headers=headers,
                timeout=10,
            )
        except (requests.Timeout, requests.ConnectionError) as exc:
            error = {
                "error": "MusicBrainz could not be reached or did not respond in time.",
                "details": type(exc).__name__,
            }
            continue
        except requests.RequestException as exc:
            return None, {
                "error": "Could not retrieve reference-track data from MusicBrainz.",
                "details": str(exc),
                "attempts": attempt,
                "action": "Tell the user the lookup failed. Do not guess the metadata.",
            }
        finally:
            _LAST_MUSICBRAINZ_REQUEST = time.monotonic()

        if response.ok:
            return response, None

        error = {
            "error": (
                "MusicBrainz is temporarily rate-limiting or unavailable."
                if response.status_code in MUSICBRAINZ_RETRYABLE_STATUS
                else "MusicBrainz rejected the lookup request."
            ),
            "status_code": response.status_code,
        }
        if response.status_code not in MUSICBRAINZ_RETRYABLE_STATUS:
            return None, {
                **error,
                "attempts": attempt,
                "action": "Tell the user the lookup failed. Do not guess the metadata.",
            }

    return None, {
        **error,
        "attempts": MUSICBRAINZ_MAX_ATTEMPTS,
        "action": (
            "Tell the user the reference lookup is temporarily unavailable and "
            "suggest trying again shortly. Do not guess the metadata."
        ),
    }


def _musicbrainz_artist_name(artist_credit: list) -> str:
    """Turn MusicBrainz artist-credit data into a readable artist string."""
    if not artist_credit:
        return "Unknown artist"

    parts = []

    for credit in artist_credit:
        name = (
            credit.get("name")
            or credit.get("artist", {}).get("name")
            or "Unknown artist"
        )

        parts.append(name)

        join_phrase = credit.get("joinphrase")
        if join_phrase:
            parts.append(join_phrase)

    return "".join(parts)


def _escape_musicbrainz_query(value: str) -> str:
    """Escape quotes/backslashes inside a MusicBrainz Lucene query."""
    return value.replace("\\", "\\\\").replace('"', '\\"')
    
def _normalize_music_text(value: str | None) -> str:
    """Normalize track/artist text for comparison."""
    if not value:
        return ""

    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def _recording_release_year(recording: dict) -> int:
    """
    Return the earliest known release year for a MusicBrainz recording.
    Unknown dates sort last.
    """
    dates = []

    first_release_date = recording.get("first-release-date")
    if first_release_date:
        dates.append(first_release_date)

    for release in recording.get("releases") or []:
        release_date = release.get("date")
        if release_date:
            dates.append(release_date)

    years = []

    for date in dates:
        match = re.match(r"(\d{4})", str(date))
        if match:
            years.append(int(match.group(1)))

    return min(years) if years else 9999


def _rank_reference_recording(
    recording: dict,
    requested_track: str,
    requested_artist: str | None,
) -> tuple:
    """
    Rank MusicBrainz search results so the likely canonical/original recording
    is preferred over later compilations, edits, remixes, or alternate versions.
    """
    result_title = recording.get("title") or ""
    result_artist = _musicbrainz_artist_name(
        recording.get("artist-credit") or []
    )

    normalized_requested_title = _normalize_music_text(requested_track)
    normalized_result_title = _normalize_music_text(result_title)

    exact_title = (
        normalized_result_title == normalized_requested_title
    )

    if requested_artist:
        exact_artist = (
            _normalize_music_text(result_artist)
            == _normalize_music_text(requested_artist)
        )
    else:
        exact_artist = True

    alternate_version_terms = (
        "remix",
        "edit",
        "radio edit",
        "live",
        "demo",
        "instrumental",
        "karaoke",
        "flip",
        "remaster",
        "acoustic",
    )

    requested_contains_version_term = any(
        term in normalized_requested_title
        for term in alternate_version_terms
    )

    result_contains_version_term = any(
        term in normalized_result_title
        for term in alternate_version_terms
    )

    unwanted_version = (
        result_contains_version_term
        and not requested_contains_version_term
    )

    release_year = _recording_release_year(recording)

    has_duration = recording.get("length") is not None

    try:
        musicbrainz_score = int(recording.get("score") or 0)
    except (TypeError, ValueError):
        musicbrainz_score = 0

    # Lower tuple values are better.
    return (
        0 if exact_title else 1,
        0 if exact_artist else 1,
        0 if not unwanted_version else 1,
        release_year,
        0 if has_duration else 1,
        -musicbrainz_score,
    )


def lookup_reference_track(
    track_name: str,
    artist: str | None = None,
) -> str:
    """
    Look up real recording metadata from MusicBrainz.

    Use this when the user names an existing song as a production reference
    and factual metadata such as track duration is needed.
    """
    if not isinstance(track_name, str) or not track_name.strip():
        return json.dumps({
            "error": "track_name must be a non-empty song title.",
            "action": "Provide the title of the reference track."
        })

    track_name = track_name.strip()

    if artist is not None:
        if not isinstance(artist, str) or not artist.strip():
            artist = None
        else:
            artist = artist.strip()

    cache_key = (_normalize_music_text(track_name), _normalize_music_text(artist))
    if cache_key in _REFERENCE_LOOKUP_CACHE:
        return _REFERENCE_LOOKUP_CACHE[cache_key]

    escaped_track = _escape_musicbrainz_query(track_name)

    if artist:
        escaped_artist = _escape_musicbrainz_query(artist)
        query = (
            f'recording:"{escaped_track}" '
            f'AND artist:"{escaped_artist}"'
        )
    else:
        query = f'recording:"{escaped_track}"'

    user_agent = os.getenv(
        "MUSICBRAINZ_USER_AGENT",
        "StudioCopilot/0.1 (Columbia University student project)"
    )

    response, error = _musicbrainz_get(
        params={
            "query": query,
            "fmt": "json",
            "limit": 5,
        },
        headers={
            "User-Agent": user_agent
        },
    )

    if error:
        return json.dumps(error)

    try:
        data = response.json()
        if not isinstance(data, dict):
            raise ValueError("unexpected JSON shape")
    except ValueError:
        return json.dumps({
            "error": "MusicBrainz returned a response that could not be parsed.",
            "action": "Try the lookup again."
        })

    recordings = data.get("recordings")
    recordings = (
        [recording for recording in recordings if isinstance(recording, dict)]
        if isinstance(recordings, list)
        else []
    )

    if not recordings:
        return json.dumps({
            "error": "No matching recordings were found.",
            "query": {
                "track_name": track_name,
                "artist": artist,
            },
            "action": (
                "Check the spelling of the title or provide the artist "
                "to make the search more specific."
            )
        })

    def summarize_recording(recording: dict) -> dict:
        length_ms = recording.get("length")

        if length_ms is not None:
            duration_seconds = length_ms / 1000.0
            duration_display = _format_timestamp(duration_seconds)
        else:
            duration_seconds = None
            duration_display = None

        releases = recording.get("releases") or []

        # Prefer an official release when MusicBrainz provides one.
        selected_release = next(
            (
                release
                for release in releases
                if release.get("status") == "Official"
            ),
            releases[0] if releases else None,
        )

        release_title = None
        release_type = None
        release_date = recording.get("first-release-date")

        if selected_release:
            release_title = selected_release.get("title")

            release_group = selected_release.get("release-group") or {}
            release_type = release_group.get("primary-type")

            if not release_date:
                release_date = selected_release.get("date")

        artist_name = _musicbrainz_artist_name(
            recording.get("artist-credit") or []
        )

        recording_id = recording.get("id")

        return {
            "title": recording.get("title"),
            "artist": artist_name,
            "duration_seconds": (
                round(duration_seconds, 2)
                if duration_seconds is not None
                else None
            ),
            "duration": duration_display,
            "first_release_date": release_date,
            "release": release_title,
            "release_type": release_type,
            "musicbrainz_id": recording_id,
            "match_score": recording.get("score"),
            "musicbrainz_url": (
                f"https://musicbrainz.org/recording/{recording_id}"
                if recording_id
                else None
            ),
        }

    ranked_recordings = sorted(
        recordings,
        key=lambda recording: _rank_reference_recording(
            recording,
            track_name,
            artist,
        ),
    )

    matches = [
        summarize_recording(recording)
        for recording in ranked_recordings
    ]

    result = {
        "query": {
            "track_name": track_name,
            "artist": artist,
        },
        "source": "MusicBrainz",
        "selected_match": matches[0],
        "alternative_matches": matches[1:3],
        "note": (
            "When multiple recordings match, Studio Copilot prefers an exact "
            "title and artist match, avoids alternate versions when possible, "
            "and favors earlier releases as the likely original recording."
        ),
    }

    result_json = json.dumps(result)
    if len(_REFERENCE_LOOKUP_CACHE) >= REFERENCE_LOOKUP_CACHE_SIZE:
        _REFERENCE_LOOKUP_CACHE.pop(next(iter(_REFERENCE_LOOKUP_CACHE)))
    _REFERENCE_LOOKUP_CACHE[cache_key] = result_json
    return result_json

def _template_correlation(a: np.ndarray, b: np.ndarray) -> float:
    """Correlation between two pitch-class profiles without NaN failures."""
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)

    a = a - np.mean(a)
    b = b - np.mean(b)

    denominator = np.linalg.norm(a) * np.linalg.norm(b)

    if denominator <= 1e-12:
        return 0.0

    return float(np.dot(a, b) / denominator)


# Below this template-correlation margin the top two key candidates are near-tied.
KEY_AMBIGUITY_MARGIN = 0.05


def _estimate_key(chroma: np.ndarray) -> dict:
    """
    Estimate the most likely major/minor key from an averaged chromagram.

    This is an estimate, not ground truth.
    """
    pitch_profile = np.mean(chroma, axis=1)

    if np.max(pitch_profile) <= 1e-10:
        return {
            "estimated_key": None,
            "template_correlation": None,
        }

    candidates = []

    for tonic in range(12):
        major_template = np.roll(MAJOR_KEY_PROFILE, tonic)
        minor_template = np.roll(MINOR_KEY_PROFILE, tonic)

        candidates.append({
            "key": f"{KEY_NAMES[tonic]} major",
            "score": _template_correlation(
                pitch_profile,
                major_template,
            ),
        })

        candidates.append({
            "key": f"{KEY_NAMES[tonic]} minor",
            "score": _template_correlation(
                pitch_profile,
                minor_template,
            ),
        })

    candidates.sort(
        key=lambda item: item["score"],
        reverse=True,
    )

    best = candidates[0]
    second = candidates[1]

    return {
        "estimated_key": best["key"],
        "template_correlation": round(best["score"], 3),
        "score_margin_over_second_choice": round(
            best["score"] - second["score"],
            3,
        ),
        "second_choice": second["key"],
    }


def _build_energy_profile(
    rms_db: np.ndarray,
    spectral_centroid: np.ndarray,
    onset_times: np.ndarray,
    duration: float,
    sr: int,
    hop_length: int,
    time_offset: float,
    segment_count: int = 8,
) -> list[dict]:
    """Summarize changes in energy/brightness/onset activity across a track."""
    frame_count = min(
        len(rms_db),
        len(spectral_centroid),
    )

    if frame_count == 0:
        return []

    frame_times = librosa.frames_to_time(
        np.arange(frame_count),
        sr=sr,
        hop_length=hop_length,
    )

    overall_rms = float(np.median(rms_db[:frame_count]))
    profile = []

    for index in range(segment_count):
        start = duration * index / segment_count
        end = duration * (index + 1) / segment_count

        mask = (
            (frame_times >= start)
            & (frame_times < end)
        )

        if not np.any(mask):
            continue

        segment_rms = float(np.median(rms_db[:frame_count][mask]))
        segment_centroid = float(
            np.median(
                spectral_centroid[:frame_count][mask]
            )
        )

        onset_count = int(
            np.sum(
                (onset_times >= start)
                & (onset_times < end)
            )
        )

        segment_duration = max(end - start, 1e-6)

        profile.append({
            "segment": index + 1,
            "start_seconds": round(
                time_offset + start,
                2,
            ),
            "end_seconds": round(
                time_offset + end,
                2,
            ),
            "median_rms_dbfs": round(
                segment_rms,
                2,
            ),
            "rms_relative_to_track_db": round(
                segment_rms - overall_rms,
                2,
            ),
            "median_spectral_centroid_hz": round(
                segment_centroid,
                1,
            ),
            "onset_density_per_second": round(
                onset_count / segment_duration,
                2,
            ),
        })

    return profile


def _candidate_structure_boundaries(
    rms_db: np.ndarray,
    spectral_centroid: np.ndarray,
    onset_env: np.ndarray,
    chroma: np.ndarray,
    duration: float,
    sr: int,
    hop_length: int,
    time_offset: float,
) -> list[dict]:
    """
    Detect large feature changes as candidate structural boundaries.

    These are intentionally labeled candidates rather than verse/chorus
    predictions.
    """
    frame_count = min(
        len(rms_db),
        len(spectral_centroid),
        len(onset_env),
        chroma.shape[1],
    )

    if frame_count < 10 or duration < 20:
        return []

    frame_times = librosa.frames_to_time(
        np.arange(frame_count),
        sr=sr,
        hop_length=hop_length,
    )

    block_seconds = 4.0
    block_count = max(
        2,
        int(np.ceil(duration / block_seconds)),
    )

    features = []
    boundary_times = []

    for block_index in range(block_count):
        start = block_index * block_seconds
        end = min(
            duration,
            (block_index + 1) * block_seconds,
        )

        mask = (
            (frame_times >= start)
            & (frame_times < end)
        )

        if not np.any(mask):
            continue

        chroma_mean = np.mean(
            chroma[:, :frame_count][:, mask],
            axis=1,
        )

        feature_vector = np.concatenate([
            np.array([
                np.median(
                    rms_db[:frame_count][mask]
                ),
                np.log1p(
                    np.median(
                        spectral_centroid[:frame_count][mask]
                    )
                ),
                np.mean(
                    onset_env[:frame_count][mask]
                ),
            ]),
            chroma_mean * 0.5,
        ])

        features.append(feature_vector)
        boundary_times.append(end)

    if len(features) < 3:
        return []

    features = np.asarray(features)

    mean = np.mean(features, axis=0)
    std = np.std(features, axis=0)
    std[std < 1e-8] = 1.0

    normalized = (features - mean) / std

    change_scores = np.linalg.norm(
        np.diff(normalized, axis=0),
        axis=1,
    )

    if np.max(change_scores) <= 1e-8:
        return []

    normalized_scores = (
        change_scores / np.max(change_scores)
    )

    ranked_indices = np.argsort(
        normalized_scores
    )[::-1]

    selected = []

    for index in ranked_indices:
        boundary_time = boundary_times[index]

        if boundary_time < 8:
            continue

        if boundary_time > duration - 8:
            continue

        if any(
            abs(boundary_time - existing["local_time"])
            < 10
            for existing in selected
        ):
            continue

        selected.append({
            "local_time": boundary_time,
            "score": float(
                normalized_scores[index]
            ),
        })

        if len(selected) >= 5:
            break

    selected.sort(
        key=lambda item: item["local_time"]
    )

    return [
        {
            "time_seconds": round(
                time_offset + item["local_time"],
                2,
            ),
            "change_strength": round(
                item["score"],
                3,
            ),
        }
        for item in selected
    ]


# --- Producer summary: deterministic, conservative interpretation ---
# Thresholds are deliberately wide so small differences read as "similar"
# instead of being exaggerated into a producer takeaway.

LEVEL_SIMILAR_DB = 1.5  # median signal levels closer than this are "about the same"
LEVEL_NOTICEABLE_DB = 4.0  # 1.5-4 dB is "slightly", 4-10 dB is "noticeably"
LEVEL_LARGE_DB = 10.0  # 10 dB or more is "much"
ACTIVITY_SIMILAR_PCT = 10.0  # onset-rate differences under this are "similar"
ACTIVITY_NOTICEABLE_PCT = 30.0  # 10-30% is "somewhat", 30%+ is "considerably"
BRIGHTNESS_SIMILAR_PCT = 8.0  # centroid differences under this are "similar"
BRIGHTNESS_NOTICEABLE_PCT = 20.0  # 8-20% is "somewhat", 20%+ is "noticeably"
TRANSITION_WINDOW_SECONDS = 6.0  # audio compared on each side of a candidate boundary
MAX_NOTABLE_OBSERVATIONS = 5
TRACK_BASELINE_CACHE_SIZE = 32

# (file name, mtime_ns, size) -> whole-track medians used as the region baseline.
_TRACK_BASELINE_CACHE: dict[tuple, dict] = {}

PRODUCER_SUMMARY_LIMITATIONS = [
    "Only entries in 'transitions' are detected feature changes; coarse window "
    "edges, the track midpoint, and selection boundaries are not transitions.",
    "Less high-frequency emphasis (a lower spectral centroid) does not show that "
    "bass, low-frequency, or low-mid content increased.",
    "Detected rhythmic activity counts attacks; it does not identify instruments, "
    "drums, or layers.",
    "Signal level is a relative measurement, not perceived loudness or LUFS.",
]


def _relative_percent(value: float | None, baseline: float | None) -> float | None:
    """Percent change from baseline, or None when the baseline is ~0."""
    if value is None or baseline is None or abs(baseline) < 1e-9:
        return None
    return (value - baseline) / abs(baseline) * 100.0


def _format_range(start: float, end: float) -> str:
    return f"{_format_timestamp(start)}–{_format_timestamp(end)}"


def _describe_relative_level(delta_db: float, target: str) -> str:
    """Phrase that reads after 'sits', e.g. 'slightly higher in average signal level than X'."""
    # Categorize the displayed (rounded) value so the label and number agree.
    delta_db = round(delta_db, 1)
    magnitude = abs(delta_db)

    if magnitude < LEVEL_SIMILAR_DB:
        return f"at about the same average signal level as {target}"

    if magnitude < LEVEL_NOTICEABLE_DB:
        degree = "slightly"
    elif magnitude < LEVEL_LARGE_DB:
        degree = "noticeably"
    else:
        degree = "much"

    direction, side = ("higher", "above") if delta_db > 0 else ("lower", "below")
    return (
        f"{degree} {direction} in average signal level than {target} "
        f"(about {magnitude:.1f} dB {side})"
    )


def _describe_rhythmic_activity(percent: float | None, target: str) -> str:
    """Phrase that reads after 'has', e.g. 'somewhat more detected rhythmic activity than X'."""
    if percent is None:
        return f"detected rhythmic activity that cannot be compared with {target}"

    percent = round(percent)
    magnitude = abs(percent)

    if magnitude < ACTIVITY_SIMILAR_PCT:
        return f"similar detected rhythmic activity to {target}"

    degree = "somewhat" if magnitude < ACTIVITY_NOTICEABLE_PCT else "considerably"
    direction = "more" if percent > 0 else "less"
    return (
        f"{degree} {direction} detected rhythmic activity than {target} "
        f"(about {magnitude:.0f}% {'more' if percent > 0 else 'fewer'} detected attacks per second)"
    )


def _describe_brightness(percent: float | None, target: str) -> str:
    """Phrase that reads after 'has'. Never implies bass, low end, warmth, or mids."""
    if percent is None:
        return f"high-frequency emphasis that cannot be compared with {target}"

    percent = round(percent)
    magnitude = abs(percent)

    if magnitude < BRIGHTNESS_SIMILAR_PCT:
        return f"similar high-frequency emphasis to {target}"

    noticeable = magnitude >= BRIGHTNESS_NOTICEABLE_PCT
    degree = "noticeably" if noticeable else "somewhat"
    direction = "more" if percent > 0 else "less"
    hearing = ""
    if noticeable:
        hearing = ", so it may sound somewhat brighter" if percent > 0 else ", so it may sound somewhat darker"

    return (
        f"{degree} {direction} high-frequency emphasis than {target}{hearing} "
        f"(brightness measure about {magnitude:.0f}% {'higher' if percent > 0 else 'lower'})"
    )


def _track_baseline(file_path: Path, y_full: np.ndarray, sr: int, hop_length: int) -> dict:
    """Whole-track medians, computed exactly like a full-track analysis and cached."""
    stat = file_path.stat()
    key = (file_path.name, stat.st_mtime_ns, stat.st_size)

    if key in _TRACK_BASELINE_CACHE:
        return _TRACK_BASELINE_CACHE[key]

    onset_env = librosa.onset.onset_strength(y=y_full, sr=sr, hop_length=hop_length)
    onset_frames = librosa.onset.onset_detect(onset_envelope=onset_env, sr=sr, hop_length=hop_length)
    rms = librosa.feature.rms(y=y_full, hop_length=hop_length)[0]
    rms_db = 20.0 * np.log10(np.maximum(rms, 1e-10))
    centroid = librosa.feature.spectral_centroid(y=y_full, sr=sr, hop_length=hop_length)[0]

    baseline = {
        "median_rms_dbfs": round(float(np.median(rms_db)), 2),
        "onset_density_per_second": round(len(onset_frames) / (len(y_full) / sr), 3),
        "median_spectral_centroid_hz": round(float(np.median(centroid)), 1),
    }
    _store_track_baseline(key, baseline)
    return baseline


def _store_track_baseline(key: tuple, baseline: dict) -> None:
    if key not in _TRACK_BASELINE_CACHE and len(_TRACK_BASELINE_CACHE) >= TRACK_BASELINE_CACHE_SIZE:
        _TRACK_BASELINE_CACHE.pop(next(iter(_TRACK_BASELINE_CACHE)))
    _TRACK_BASELINE_CACHE[key] = baseline


def _describe_transitions(
    boundaries: list[dict],
    rms_db: np.ndarray,
    spectral_centroid: np.ndarray,
    onset_times: np.ndarray,
    sr: int,
    hop_length: int,
    time_offset: float,
    duration: float,
) -> list[dict]:
    """Describe what measurably changes across each detected candidate boundary.

    Only candidate_structure_boundaries are used, so a transition is never
    reported at a window edge, midpoint, or selection boundary.
    """
    frame_count = min(len(rms_db), len(spectral_centroid))
    frame_times = librosa.frames_to_time(np.arange(frame_count), sr=sr, hop_length=hop_length)
    rms_db = rms_db[:frame_count]
    spectral_centroid = spectral_centroid[:frame_count]
    transitions = []

    for boundary in boundaries:
        time_seconds = boundary["time_seconds"]
        local = time_seconds - time_offset
        before = (max(0.0, local - TRANSITION_WINDOW_SECONDS), local)
        after = (local, min(duration, local + TRANSITION_WINDOW_SECONDS))
        entry = {
            "time_seconds": time_seconds,
            "timestamp": _format_timestamp(time_seconds),
            "change_strength": boundary["change_strength"],
            "level_change_db": None,
            "onset_change_percent": None,
            "centroid_change_percent": None,
        }
        text = (
            f"A candidate feature change is detected at {entry['timestamp']} "
            f"(detector strength {boundary['change_strength']:.2f})."
        )

        mask_before = (frame_times >= before[0]) & (frame_times < before[1])
        mask_after = (frame_times >= after[0]) & (frame_times < after[1])

        if (
            before[1] - before[0] >= 1.0
            and after[1] - after[0] >= 1.0
            and np.any(mask_before)
            and np.any(mask_after)
        ):
            level_change = float(np.median(rms_db[mask_after]) - np.median(rms_db[mask_before]))
            rate_before = float(np.sum((onset_times >= before[0]) & (onset_times < before[1]))) / (before[1] - before[0])
            rate_after = float(np.sum((onset_times >= after[0]) & (onset_times < after[1]))) / (after[1] - after[0])
            onset_change = _relative_percent(rate_after, rate_before)
            centroid_change = _relative_percent(
                float(np.median(spectral_centroid[mask_after])),
                float(np.median(spectral_centroid[mask_before])),
            )
            entry["level_change_db"] = round(level_change, 1)
            entry["onset_change_percent"] = None if onset_change is None else round(onset_change, 1)
            entry["centroid_change_percent"] = None if centroid_change is None else round(centroid_change, 1)

            target = f"the {TRANSITION_WINDOW_SECONDS:.0f} seconds before it"
            text += (
                f" The {TRANSITION_WINDOW_SECONDS:.0f} seconds after it sit "
                f"{_describe_relative_level(level_change, target)}, have "
                f"{_describe_rhythmic_activity(onset_change, target)}, and have "
                f"{_describe_brightness(centroid_change, target)}."
            )

        entry["text"] = text
        transitions.append(entry)

    return transitions


def _window_name(index: int, count: int, segment: dict) -> str:
    if index == 0:
        return "opening"
    if index == count - 1:
        return "ending"
    return f"window from {_format_range(segment['start_seconds'], segment['end_seconds'])}"


def _window_fields(segment: dict) -> dict:
    return {
        "segment": segment["segment"],
        "start_seconds": segment["start_seconds"],
        "end_seconds": segment["end_seconds"],
    }


def _rank_observations(candidates: list[tuple[float, dict]]) -> list[dict]:
    ranked = sorted(candidates, key=lambda item: item[0], reverse=True)
    return [observation for _, observation in ranked[:MAX_NOTABLE_OBSERVATIONS]]


def _build_full_track_summary(profile: list[dict], baseline: dict, transitions: list[dict]) -> dict:
    """Notable, verified facts about the whole track from its coarse windows."""
    summary = {
        "scope": "full_track",
        "baseline": baseline,
        "notable_observations": [],
        "level": {},
        "rhythmic_activity": {},
        "brightness": {},
        "transitions": transitions,
        "limitations": PRODUCER_SUMMARY_LIMITATIONS,
    }

    if not profile:
        return summary

    count = len(profile)
    track_rms = baseline["median_rms_dbfs"]
    track_onsets = baseline["onset_density_per_second"]
    track_centroid = baseline["median_spectral_centroid_hz"]

    level_delta = [segment["median_rms_dbfs"] - track_rms for segment in profile]
    onset_pct = [_relative_percent(segment["onset_density_per_second"], track_onsets) for segment in profile]
    centroid_pct = [_relative_percent(segment["median_spectral_centroid_hz"], track_centroid) for segment in profile]

    middle = profile[1:-1] if count >= 3 else []
    middle_median = float(np.median([segment["median_rms_dbfs"] for segment in middle])) if middle else None

    candidates = []

    # ---------- Level ----------
    edges = [("opening", 0)] + ([("ending", count - 1)] if count >= 2 else [])
    for name, index in edges:
        segment = profile[index]
        delta = level_delta[index]
        versus_middle = None if middle_median is None else segment["median_rms_dbfs"] - middle_median

        summary["level"][name] = {
            **_window_fields(segment),
            "relative_to_track_median_db": round(delta, 1),
            "relative_to_middle_windows_db": None if versus_middle is None else round(versus_middle, 1),
            "description": f"The {name} sits {_describe_relative_level(delta, 'the track-wide median')}.",
        }

        if abs(delta) >= LEVEL_SIMILAR_DB:
            text = (
                f"The {name} ({_format_range(segment['start_seconds'], segment['end_seconds'])}) sits "
                f"{_describe_relative_level(delta, 'the track-wide median')}"
            )
            if versus_middle is not None and abs(versus_middle) >= LEVEL_SIMILAR_DB:
                text += (
                    f", and about {abs(versus_middle):.1f} dB {'above' if versus_middle > 0 else 'below'} "
                    f"the median level of the middle windows "
                    f"({_format_range(middle[0]['start_seconds'], middle[-1]['end_seconds'])})"
                )
            candidates.append((abs(delta) / LEVEL_NOTICEABLE_DB, {
                "type": "level",
                **_window_fields(segment),
                "values": {
                    "relative_to_track_median_db": round(delta, 1),
                    "relative_to_middle_windows_db": None if versus_middle is None else round(versus_middle, 1),
                },
                "text": text + ".",
            }))

    if middle_median is not None:
        summary["level"]["middle_windows"] = {
            "segments": f"{middle[0]['segment']}-{middle[-1]['segment']}",
            "start_seconds": middle[0]["start_seconds"],
            "end_seconds": middle[-1]["end_seconds"],
            "median_of_window_levels_dbfs": round(middle_median, 2),
        }

    lowest = min(range(count), key=lambda i: profile[i]["median_rms_dbfs"])
    highest = max(range(count), key=lambda i: profile[i]["median_rms_dbfs"])
    summary["level"]["lowest_window"] = {**_window_fields(profile[lowest]), "relative_to_track_median_db": round(level_delta[lowest], 1)}
    summary["level"]["highest_window"] = {**_window_fields(profile[highest]), "relative_to_track_median_db": round(level_delta[highest], 1)}

    # ---------- Rhythmic activity ----------
    most_active = max(range(count), key=lambda i: profile[i]["onset_density_per_second"])
    least_active = min(range(count), key=lambda i: profile[i]["onset_density_per_second"])

    for key, index, rank in (("most_active_window", most_active, "highest"), ("least_active_window", least_active, "lowest")):
        summary["rhythmic_activity"][key] = {
            **_window_fields(profile[index]),
            "onsets_per_second": profile[index]["onset_density_per_second"],
            "relative_to_track_percent": None if onset_pct[index] is None else round(onset_pct[index], 1),
            "rank": f"{rank} of {count} coarse windows",
        }

    for name, index in edges:
        summary["rhythmic_activity"][name] = {
            "relative_to_track_percent": None if onset_pct[index] is None else round(onset_pct[index], 1),
            "description": f"The {name} has {_describe_rhythmic_activity(onset_pct[index], 'the track average')}.",
        }

    # Quiet windows that are still rhythmically active are easy to misread as sparse.
    contrast_windows = set()
    for index, segment in enumerate(profile):
        pct = onset_pct[index]
        if level_delta[index] <= -LEVEL_LARGE_DB and pct is not None and pct >= 0:
            contrast_windows.add(index)
            rank_clause = (
                f", the highest detected attack rate of the {count} coarse windows"
                if index == most_active else ""
            )
            candidates.append((abs(level_delta[index]) / LEVEL_NOTICEABLE_DB + 0.5, {
                "type": "level_activity_contrast",
                **_window_fields(segment),
                "values": {
                    "relative_to_track_median_db": round(level_delta[index], 1),
                    "onset_relative_to_track_percent": round(pct, 1),
                },
                "text": (
                    f"Although the {_window_name(index, count, segment)} sits about "
                    f"{abs(level_delta[index]):.1f} dB below the track-wide median level, it is not "
                    f"rhythmically sparse: it has {_describe_rhythmic_activity(pct, 'the track average')}"
                    f"{rank_clause}."
                ),
            }))

    for index, rank, threshold_ok in (
        (most_active, "highest", onset_pct[most_active] is not None and onset_pct[most_active] >= ACTIVITY_SIMILAR_PCT),
        (least_active, "lowest", onset_pct[least_active] is not None and onset_pct[least_active] <= -ACTIVITY_SIMILAR_PCT),
    ):
        if not threshold_ok or index in contrast_windows:
            continue
        pct = onset_pct[index]
        candidates.append((abs(pct) / ACTIVITY_NOTICEABLE_PCT, {
            "type": "rhythmic_activity",
            **_window_fields(profile[index]),
            "values": {"onset_relative_to_track_percent": round(pct, 1)},
            "text": (
                f"The {_window_name(index, count, profile[index])} has the {rank} detected rhythmic "
                f"activity of the {count} coarse windows (about {abs(pct):.0f}% "
                f"{'above' if pct > 0 else 'below'} the track average)."
            ),
        }))

    # ---------- Brightness ----------
    brightest = max(range(count), key=lambda i: profile[i]["median_spectral_centroid_hz"])
    darkest = min(range(count), key=lambda i: profile[i]["median_spectral_centroid_hz"])

    for key, index, rank in (("brightest_window", brightest, "most"), ("darkest_window", darkest, "least")):
        summary["brightness"][key] = {
            **_window_fields(profile[index]),
            "relative_to_track_percent": None if centroid_pct[index] is None else round(centroid_pct[index], 1),
            "rank": f"{rank} high-frequency emphasis of {count} coarse windows",
        }

    for name, index in edges:
        summary["brightness"][name] = {
            "relative_to_track_percent": None if centroid_pct[index] is None else round(centroid_pct[index], 1),
            "description": f"The {name} has {_describe_brightness(centroid_pct[index], 'the track as a whole')}.",
        }

    for index, rank, threshold_ok in (
        (brightest, "most", centroid_pct[brightest] is not None and centroid_pct[brightest] >= BRIGHTNESS_SIMILAR_PCT),
        (darkest, "least", centroid_pct[darkest] is not None and centroid_pct[darkest] <= -BRIGHTNESS_SIMILAR_PCT),
    ):
        if not threshold_ok:
            continue
        pct = centroid_pct[index]
        candidates.append((abs(pct) / BRIGHTNESS_NOTICEABLE_PCT, {
            "type": "brightness",
            **_window_fields(profile[index]),
            "values": {"centroid_relative_to_track_percent": round(pct, 1)},
            "text": (
                f"The {_window_name(index, count, profile[index])} has the {rank} high-frequency "
                f"emphasis of the {count} coarse windows (brightness measure about {abs(pct):.0f}% "
                f"{'above' if pct > 0 else 'below'} the track median)."
            ),
        }))

    # ---------- Transitions ----------
    if transitions:
        strongest = max(transitions, key=lambda item: item["change_strength"])
        candidates.append((1.0 + strongest["change_strength"], {
            "type": "transition",
            "start_seconds": strongest["time_seconds"],
            "end_seconds": strongest["time_seconds"],
            "values": {
                "change_strength": strongest["change_strength"],
                "level_change_db": strongest["level_change_db"],
                "onset_change_percent": strongest["onset_change_percent"],
                "centroid_change_percent": strongest["centroid_change_percent"],
            },
            "text": f"Strongest of {len(transitions)} candidate transitions. {strongest['text']}",
        }))

    summary["notable_observations"] = _rank_observations(candidates)
    return summary


def _build_region_summary(
    region_rms: float,
    region_onsets: float,
    region_centroid: float,
    profile: list[dict],
    baseline: dict,
    transitions: list[dict],
    start: float,
    end: float,
) -> dict:
    """Verified facts about an exact region, relative to the whole track."""
    level_delta = region_rms - baseline["median_rms_dbfs"]
    onset_pct = _relative_percent(region_onsets, baseline["onset_density_per_second"])
    centroid_pct = _relative_percent(region_centroid, baseline["median_spectral_centroid_hz"])
    region_label = f"This region ({_format_range(start, end)})"
    track = "the track as a whole"

    dips = []
    for segment in profile:
        relative = segment["rms_relative_to_track_db"]
        if relative > -LEVEL_NOTICEABLE_DB:
            continue
        activity = _relative_percent(segment["onset_density_per_second"], region_onsets)
        dips.append({
            **_window_fields(segment),
            "relative_to_region_median_db": round(relative, 1),
            "onset_relative_to_region_percent": None if activity is None else round(activity, 1),
            "text": (
                f"The signal level dips temporarily from "
                f"{_format_range(segment['start_seconds'], segment['end_seconds'])} (about "
                f"{abs(relative):.1f} dB below this region's median level); that window has "
                f"{_describe_rhythmic_activity(activity, 'the region as a whole')}."
            ),
        })

    summary = {
        "scope": "region",
        "baseline": baseline,
        "notable_observations": [],
        "level": {
            "relative_to_track_median_db": round(level_delta, 1),
            "description": f"{region_label} sits {_describe_relative_level(level_delta, 'the track-wide median')}.",
            "temporary_dips": dips,
        },
        "rhythmic_activity": {
            "relative_to_track_percent": None if onset_pct is None else round(onset_pct, 1),
            "description": f"{region_label} has {_describe_rhythmic_activity(onset_pct, 'the track average')}.",
        },
        "brightness": {
            "relative_to_track_percent": None if centroid_pct is None else round(centroid_pct, 1),
            "description": f"{region_label} has {_describe_brightness(centroid_pct, track)}.",
        },
        "transitions": transitions,
        "limitations": PRODUCER_SUMMARY_LIMITATIONS,
    }

    candidates = []
    if abs(level_delta) >= LEVEL_SIMILAR_DB:
        candidates.append((abs(level_delta) / LEVEL_NOTICEABLE_DB, {
            "type": "level", "start_seconds": start, "end_seconds": end,
            "values": {"relative_to_track_median_db": round(level_delta, 1)},
            "text": summary["level"]["description"],
        }))
    if onset_pct is not None and abs(onset_pct) >= ACTIVITY_SIMILAR_PCT:
        candidates.append((abs(onset_pct) / ACTIVITY_NOTICEABLE_PCT, {
            "type": "rhythmic_activity", "start_seconds": start, "end_seconds": end,
            "values": {"onset_relative_to_track_percent": round(onset_pct, 1)},
            "text": summary["rhythmic_activity"]["description"],
        }))
    if centroid_pct is not None and abs(centroid_pct) >= BRIGHTNESS_SIMILAR_PCT:
        candidates.append((abs(centroid_pct) / BRIGHTNESS_NOTICEABLE_PCT, {
            "type": "brightness", "start_seconds": start, "end_seconds": end,
            "values": {"centroid_relative_to_track_percent": round(centroid_pct, 1)},
            "text": summary["brightness"]["description"],
        }))
    if dips:
        deepest = min(dips, key=lambda item: item["relative_to_region_median_db"])
        candidates.append((abs(deepest["relative_to_region_median_db"]) / LEVEL_NOTICEABLE_DB, {
            "type": "temporary_dip",
            "start_seconds": deepest["start_seconds"], "end_seconds": deepest["end_seconds"],
            "values": {
                "relative_to_region_median_db": deepest["relative_to_region_median_db"],
                "onset_relative_to_region_percent": deepest["onset_relative_to_region_percent"],
            },
            "text": deepest["text"],
        }))
    for transition in transitions:
        candidates.append((1.0 + transition["change_strength"], {
            "type": "transition",
            "start_seconds": transition["time_seconds"], "end_seconds": transition["time_seconds"],
            "values": {
                "change_strength": transition["change_strength"],
                "level_change_db": transition["level_change_db"],
                "onset_change_percent": transition["onset_change_percent"],
                "centroid_change_percent": transition["centroid_change_percent"],
            },
            "text": transition["text"],
        }))

    summary["notable_observations"] = _rank_observations(candidates)
    return summary


def analyze_audio_track(
    audio_file_id: str,
    start_seconds: float | None = None,
    end_seconds: float | None = None,
) -> str:
    """
    Analyze an uploaded musical audio file or a selected region.

    Returns deterministic audio features that Gemini can interpret
    in producer-oriented language.
    """
    try:
        if not isinstance(audio_file_id, str):
            return json.dumps({
                "error": "audio_file_id must be a string."
            })

        # Prevent path traversal.
        safe_file_id = Path(audio_file_id).name

        if safe_file_id != audio_file_id:
            return json.dumps({
                "error": "Invalid audio file ID."
            })

        file_path = AUDIO_UPLOAD_DIR / safe_file_id

        if not file_path.exists():
            return json.dumps({
                "error": "The uploaded audio file could not be found.",
                "action": (
                    "Upload or re-attach the audio file before "
                    "requesting analysis."
                ),
            })

        supported_extensions = {
            ".wav",
            ".mp3",
            ".flac",
            ".ogg",
        }

        if file_path.suffix.lower() not in supported_extensions:
            return json.dumps({
                "error": (
                    f"Unsupported audio format: "
                    f"{file_path.suffix}"
                ),
                "action": (
                    "Use WAV, MP3, FLAC, or OGG."
                ),
            })

        # Librosa's default 22.05 kHz mono representation is enough
        # for these high-level MIR features and keeps analysis fast.
        y_full, sr = librosa.load(
            str(file_path),
            sr=22050,
            mono=True,
        )

        if len(y_full) == 0:
            return json.dumps({
                "error": "The uploaded audio file contains no audio samples."
            })

        full_duration = len(y_full) / sr
        _AUDIO_DURATION_CACHE[safe_file_id] = full_duration

        for name, value in (("start_seconds", start_seconds), ("end_seconds", end_seconds)):
            if value is None:
                continue
            if (
                isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not math.isfinite(value)
            ):
                return json.dumps({
                    "error": f"{name} must be a finite number of seconds.",
                    "action": (
                        "Convert MM:SS timestamps to seconds (e.g. 1:10 -> 70) "
                        "or omit the range to analyze the whole track."
                    ),
                })

        start = (
            float(start_seconds)
            if start_seconds is not None
            else 0.0
        )

        end = (
            float(end_seconds)
            if end_seconds is not None
            else full_duration
        )

        if start < 0:
            return json.dumps({
                "error": "start_seconds cannot be negative."
            })

        if end <= start:
            return json.dumps({
                "error": (
                    "end_seconds must be greater than start_seconds."
                )
            })

        out_of_range_action = (
            "Tell the user the requested region is outside the track and "
            "ask for a range within 0 to "
            f"{round(full_duration, 2)} seconds. Do not analyze a "
            "different range in its place."
        )

        if start >= full_duration:
            return json.dumps({
                "error": (
                    f"start_seconds ({round(start, 2)}) is beyond the end "
                    f"of the audio file ({round(full_duration, 2)} seconds)."
                ),
                "requested_range": {
                    "start_seconds": round(start, 2),
                    "end_seconds": round(end, 2),
                },
                "full_duration_seconds": round(
                    full_duration,
                    2,
                ),
                "action": out_of_range_action,
            })

        if end > full_duration + RANGE_END_TOLERANCE_SECONDS:
            return json.dumps({
                "error": (
                    f"end_seconds ({round(end, 2)}) is beyond the end "
                    f"of the audio file ({round(full_duration, 2)} seconds)."
                ),
                "requested_range": {
                    "start_seconds": round(start, 2),
                    "end_seconds": round(end, 2),
                },
                "full_duration_seconds": round(
                    full_duration,
                    2,
                ),
                "action": out_of_range_action,
            })

        end = min(
            end,
            full_duration,
        )

        start_sample = int(start * sr)
        end_sample = int(end * sr)

        y = y_full[start_sample:end_sample]

        duration = len(y) / sr

        if duration < 1:
            return json.dumps({
                "error": (
                    "The selected analysis region is too short."
                ),
                "action": (
                    "Analyze at least one second of audio."
                ),
            })

        peak_amplitude = float(
            np.max(np.abs(y))
        )

        if peak_amplitude < 1e-7:
            return json.dumps({
                "error": (
                    "The selected audio region is effectively silent."
                )
            })

        hop_length = 1024

        # ---------- Rhythm ----------

        onset_env = librosa.onset.onset_strength(
            y=y,
            sr=sr,
            hop_length=hop_length,
        )

        tempo, beat_frames = librosa.beat.beat_track(
            onset_envelope=onset_env,
            sr=sr,
            hop_length=hop_length,
        )

        estimated_bpm = float(
            np.asarray(tempo).reshape(-1)[0]
        )

        onset_frames = librosa.onset.onset_detect(
            onset_envelope=onset_env,
            sr=sr,
            hop_length=hop_length,
        )

        onset_times = librosa.frames_to_time(
            onset_frames,
            sr=sr,
            hop_length=hop_length,
        )

        # ---------- Dynamics ----------

        rms = librosa.feature.rms(
            y=y,
            hop_length=hop_length,
        )[0]

        rms_db = 20.0 * np.log10(
            np.maximum(
                rms,
                1e-10,
            )
        )

        peak_dbfs = 20.0 * np.log10(
            max(
                peak_amplitude,
                1e-10,
            )
        )

        median_rms_dbfs = float(
            np.median(rms_db)
        )

        rms_p10 = float(
            np.percentile(rms_db, 10)
        )

        rms_p90 = float(
            np.percentile(rms_db, 90)
        )

        # ---------- Spectral brightness ----------

        spectral_centroid = (
            librosa.feature.spectral_centroid(
                y=y,
                sr=sr,
                hop_length=hop_length,
            )[0]
        )

        # ---------- Harmony / key ----------

        chroma = librosa.feature.chroma_cqt(
            y=y,
            sr=sr,
            hop_length=hop_length,
        )

        key_estimate = _estimate_key(
            chroma
        )

        # ---------- Profiles ----------

        energy_profile = _build_energy_profile(
            rms_db=rms_db,
            spectral_centroid=spectral_centroid,
            onset_times=onset_times,
            duration=duration,
            sr=sr,
            hop_length=hop_length,
            time_offset=start,
        )

        boundaries = _candidate_structure_boundaries(
            rms_db=rms_db,
            spectral_centroid=spectral_centroid,
            onset_env=onset_env,
            chroma=chroma,
            duration=duration,
            sr=sr,
            hop_length=hop_length,
            time_offset=start,
        )

        result = {
            "audio_file_id": audio_file_id,

            "full_track_duration_seconds": round(
                full_duration,
                2,
            ),

            "analysis_range": {
                "start_seconds": round(
                    start,
                    2,
                ),
                "end_seconds": round(
                    end,
                    2,
                ),
                "duration_seconds": round(
                    duration,
                    2,
                ),
            },

            "rhythm": {
                "estimated_bpm": round(
                    estimated_bpm,
                    2,
                ),
                "detected_beat_count": int(
                    len(beat_frames)
                ),
                "onset_count": int(
                    len(onset_times)
                ),
                "onset_density_per_second": round(
                    len(onset_times) / duration,
                    3,
                ),
            },

            "key": key_estimate,

            "dynamics": {
                "peak_dbfs": round(
                    peak_dbfs,
                    2,
                ),
                "median_rms_dbfs": round(
                    median_rms_dbfs,
                    2,
                ),
                "rms_p10_dbfs": round(
                    rms_p10,
                    2,
                ),
                "rms_p90_dbfs": round(
                    rms_p90,
                    2,
                ),
                "rms_variation_p90_minus_p10_db": round(
                    rms_p90 - rms_p10,
                    2,
                ),
                "crest_factor_proxy_db": round(
                    peak_dbfs - median_rms_dbfs,
                    2,
                ),
            },

            "spectral": {
                "median_spectral_centroid_hz": round(
                    float(
                        np.median(
                            spectral_centroid
                        )
                    ),
                    1,
                )
            },

            "energy_profile": energy_profile,

            "candidate_structure_boundaries": boundaries,

            "interpretation_notes": [
                (
                    "Tempo and key are algorithmic estimates and may be "
                    "incorrect for rhythmically ambiguous or harmonically "
                    "complex material."
                ),
                (
                    "RMS values are signal-level measurements in dBFS for "
                    "relative comparison, not LUFS or perceived loudness."
                ),
                (
                    "crest_factor_proxy_db is a rough peak-to-average contrast. "
                    "It is not headroom and not musical dynamic range."
                ),
                (
                    "Onset density and spectral centroid describe rhythmic "
                    "activity and brightness only; they do not identify "
                    "instruments, layers, EQ, or low-end balance."
                ),
                (
                    "Candidate structure boundaries indicate relatively "
                    "large audio-feature changes. They do not automatically "
                    "identify verses, choruses, or drops."
                ),
            ],
        }

        key_margin = key_estimate.get("score_margin_over_second_choice")
        if (
            key_estimate.get("estimated_key")
            and isinstance(key_margin, (int, float))
            and key_margin < KEY_AMBIGUITY_MARGIN
        ):
            result["interpretation_notes"].insert(0, (
                f"Key estimate is ambiguous: {key_estimate['estimated_key']} and "
                f"{key_estimate.get('second_choice')} score almost equally. "
                "Present the key as uncertain."
            ))

        is_full_track = start <= 0.5 and end >= full_duration - 0.5

        result["interpretation_notes"].append(
            "producer_summary is a deterministic, conservative interpretation of these "
            "measurements. Use it as the primary basis for producer-facing explanations "
            "and keep its direction and magnitude; use the raw fields for technical detail."
        )
        if not is_full_track:
            result["interpretation_notes"].append(
                "In this region analysis, energy_profile rms_relative_to_track_db is relative "
                "to this region's median, not the whole track; producer_summary.baseline "
                "holds the whole-track values."
            )

        try:
            transitions = _describe_transitions(
                boundaries=boundaries,
                rms_db=rms_db,
                spectral_centroid=spectral_centroid,
                onset_times=onset_times,
                sr=sr,
                hop_length=hop_length,
                time_offset=start,
                duration=duration,
            )

            if is_full_track:
                baseline = {
                    "median_rms_dbfs": result["dynamics"]["median_rms_dbfs"],
                    "onset_density_per_second": result["rhythm"]["onset_density_per_second"],
                    "median_spectral_centroid_hz": result["spectral"]["median_spectral_centroid_hz"],
                }
                stat = file_path.stat()
                _store_track_baseline((file_path.name, stat.st_mtime_ns, stat.st_size), baseline)
                producer_summary = _build_full_track_summary(energy_profile, baseline, transitions)
            else:
                producer_summary = _build_region_summary(
                    region_rms=result["dynamics"]["median_rms_dbfs"],
                    region_onsets=result["rhythm"]["onset_density_per_second"],
                    region_centroid=result["spectral"]["median_spectral_centroid_hz"],
                    profile=energy_profile,
                    baseline=_track_baseline(file_path, y_full, sr, hop_length),
                    transitions=transitions,
                    start=round(start, 2),
                    end=round(end, 2),
                )
        except Exception as exc:
            producer_summary = {
                "unavailable": (
                    f"producer_summary could not be computed ({type(exc).__name__}). "
                    "Rely on the raw fields and interpretation_notes."
                )
            }

        result["producer_summary"] = producer_summary

        return json.dumps(result)

    except Exception as exc:
        return json.dumps({
            "error": "Audio analysis failed.",
            "details": (
                f"{type(exc).__name__}: {str(exc)}"
            ),
            "action": (
                "Confirm that the uploaded file is valid WAV, MP3, "
                "FLAC, or OGG audio and try again."
            ),
        })


FOCUS_LABEL_MAX_CHARS = 40
FOCUS_REASON_MAX_CHARS = 280


def _as_finite_number(value) -> float | None:
    """Return value as a finite float, or None for bools, strings, NaN, etc."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None

    value = float(value)
    return value if math.isfinite(value) else None


def focus_audio_region(
    audio_file_id: str,
    start_seconds: float,
    end_seconds: float,
    label: str,
    reason: str,
) -> str:
    """
    Direct the user's visual attention to a time region in the Track View.

    This performs no audio analysis. The frontend highlights the returned
    range over the waveform/spectrogram.
    """
    try:
        file_path = resolve_uploaded_audio(audio_file_id)
    except ValueError:
        return json.dumps({
            "error": "Invalid audio file ID.",
            "action": (
                "Use the exact audio_file_id from the attached audio context."
            ),
        })
    except FileNotFoundError:
        return json.dumps({
            "error": "The uploaded audio file could not be found.",
            "action": (
                "Ask the user to upload or re-attach the audio file."
            ),
        })

    start = _as_finite_number(start_seconds)
    end = _as_finite_number(end_seconds)

    if start is None or end is None:
        return json.dumps({
            "error": "start_seconds and end_seconds must both be numbers in seconds.",
            "action": (
                "Convert MM:SS timestamps to seconds, e.g. 1:10 -> 70."
            ),
        })

    if start < 0:
        return json.dumps({
            "error": "start_seconds cannot be negative.",
            "action": "Use a start time of 0 seconds or later.",
        })

    if end <= start:
        return json.dumps({
            "error": "end_seconds must be greater than start_seconds.",
            "action": "Provide a region whose end is after its start.",
        })

    try:
        full_duration = get_audio_duration(file_path)
    except Exception:
        full_duration = None

    if full_duration is not None:
        if start >= full_duration or end > full_duration + RANGE_END_TOLERANCE_SECONDS:
            return json.dumps({
                "error": (
                    f"The region {round(start, 2)}-{round(end, 2)} seconds "
                    f"is outside the track ({round(full_duration, 2)} seconds)."
                ),
                "full_track_duration_seconds": round(full_duration, 2),
                "action": (
                    "Choose a region within the track. Do not substitute a "
                    "different region without telling the user."
                ),
            })

        end = min(end, full_duration)

    if not isinstance(label, str) or not label.strip():
        return json.dumps({
            "error": "label must be a short non-empty string.",
            "action": "Provide a neutral label such as 'Energy dip'.",
        })

    reason = reason.strip() if isinstance(reason, str) else ""

    return json.dumps({
        "audio_file_id": audio_file_id,
        "start_seconds": round(start, 2),
        "end_seconds": round(end, 2),
        "label": label.strip()[:FOCUS_LABEL_MAX_CHARS],
        "reason": reason[:FOCUS_REASON_MAX_CHARS],
        "full_track_duration_seconds": (
            round(full_duration, 2) if full_duration is not None else None
        ),
    })


SPECTROGRAM_WIDTH_PX = 1600
SPECTROGRAM_MEL_BANDS = 128
SPECTROGRAM_CACHE_VERSION = "v1"

# Near-black -> deep blue -> teal -> Studio Copilot green -> pale highlight.
SPECTROGRAM_COLORS = [
    (0.00, "#06090e"),
    (0.25, "#0d2240"),
    (0.50, "#11607a"),
    (0.75, "#3fbf8f"),
    (0.92, "#9df27c"),
    (1.00, "#effbe6"),
]


def render_spectrogram_png(audio_file_id: str) -> Path:
    """
    Render (or reuse a cached) mel spectrogram PNG for an uploaded file.

    Column k of the image covers [k/W * D, (k+1)/W * D) seconds, so the image's
    left edge is 0 s and its right edge is the full duration D. Low
    frequencies are at the bottom. Not an LLM tool.
    """
    file_path = resolve_uploaded_audio(audio_file_id)

    cache_path = SPECTROGRAM_CACHE_DIR / (
        f"{file_path.stem}_{SPECTROGRAM_CACHE_VERSION}.png"
    )

    if cache_path.is_file():
        return cache_path

    import matplotlib

    matplotlib.use("Agg")

    from matplotlib.colors import LinearSegmentedColormap
    from matplotlib.image import imsave

    y, sr = librosa.load(str(file_path), sr=22050, mono=True)

    if len(y) == 0:
        raise ValueError("The uploaded audio file contains no audio samples.")

    duration = len(y) / sr
    _AUDIO_DURATION_CACHE[file_path.name] = duration

    hop_length = 512

    mel = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_fft=2048,
        hop_length=hop_length,
        n_mels=SPECTROGRAM_MEL_BANDS,
        fmax=sr / 2,
    )

    mel_db = librosa.power_to_db(mel, ref=np.max, top_db=80.0)
    normalized = np.clip((mel_db + 80.0) / 80.0, 0.0, 1.0)

    frame_times = librosa.frames_to_time(
        np.arange(normalized.shape[1]),
        sr=sr,
        hop_length=hop_length,
    )

    width = SPECTROGRAM_WIDTH_PX
    edges = np.linspace(0.0, duration, width + 1)
    first_frames = np.searchsorted(frame_times, edges[:-1], side="left")
    last_frames = np.searchsorted(frame_times, edges[1:], side="left")

    image = np.empty((normalized.shape[0], width), dtype=np.float32)
    max_frame = normalized.shape[1] - 1

    for column in range(width):
        first = first_frames[column]
        last = last_frames[column]

        if last > first:
            image[:, column] = normalized[:, first:last].mean(axis=1)
        else:
            # Short files: more columns than frames, so use the nearest frame.
            center = (edges[column] + edges[column + 1]) / 2
            nearest = int(round(center * sr / hop_length))
            image[:, column] = normalized[:, min(max(nearest, 0), max_frame)]

    colormap = LinearSegmentedColormap.from_list(
        "studio_copilot",
        SPECTROGRAM_COLORS,
    )

    temp_path = cache_path.with_name(
        f"{cache_path.stem}.{os.getpid()}.{time.monotonic_ns()}.tmp.png"
    )

    try:
        imsave(
            temp_path,
            image,
            cmap=colormap,
            vmin=0.0,
            vmax=1.0,
            origin="lower",
            format="png",
        )
        os.replace(temp_path, cache_path)
    finally:
        temp_path.unlink(missing_ok=True)

    return cache_path


# What Gemini sees. Descriptions should explain WHEN the tool is useful, not just what it computes.
TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "transform_sample",
            "description": (
                "Calculate the exact tempo/time-stretch and optional pitch-shift changes needed "
                "to fit an existing musical sample or loop into a target production. Use this "
                "whenever the user wants to adapt a sample from one BPM to another, from one key "
                "to another, or both. If the user gives a loop length in bars, include it so the "
                "tool can return before/after durations. Do not estimate this math yourself when "
                "the needed values are available."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "source_bpm": {
                        "type": "number",
                        "description": "Original tempo of the sample in BPM, e.g. 92.",
                    },
                    "target_bpm": {
                        "type": "number",
                        "description": "Tempo of the destination track in BPM, e.g. 124.",
                    },
                    "source_key": {
                        "type": "string",
                        "description": "Optional original musical key, e.g. 'D minor', 'Dm', or 'F# major'.",
                    },
                    "target_key": {
                        "type": "string",
                        "description": "Optional destination musical key, e.g. 'F minor' or 'Ab major'.",
                    },
                    "bars": {
                        "type": "integer",
                        "description": "Optional length of the sample in bars, e.g. 8.",
                    },
                    "beats_per_bar": {
                        "type": "integer",
                        "description": "Beats per bar. Use 4 unless the user specifies another meter.",
                        "default": 4,
                    },
                },
                "required": ["source_bpm", "target_bpm"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "build_arrangement",
            "description": (
                "Create a mathematically bar-accurate song arrangement for a "
                "specified BPM, target duration, and ordered set of song sections. "
                "Use this when a musician or producer wants to create, restructure, "
                "shorten, lengthen, or plan the timeline of a song. Section "
                "boundaries are aligned to musically practical four-bar blocks. "
                "The sections argument should contain the exact ordered sections "
                "the user wants, including repeated sections such as two verses "
                "or two choruses."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "bpm": {
                        "type": "number",
                        "description": "The tempo of the track in beats per minute."
                    },
                    "target_duration_seconds": {
                        "type": "number",
                        "description": (
                            "Desired total song duration in seconds. "
                            "For example, 3 minutes 30 seconds should be passed as 210."
                        )
                    },
                    "sections": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": (
                            "Ordered song sections. Repeated sections should appear "
                            "multiple times. Example: "
                            "['intro', 'verse 1', 'chorus 1', 'verse 2', "
                            "'chorus 2', 'bridge', 'final chorus', 'outro']."
                        )
                    },
                    "time_signature": {
                        "type": "string",
                        "description": (
                            "Song time signature. Defaults to 4/4. "
                            "Currently supports quarter-note based meters."
                        ),
                        "default": "4/4"
                    }
                },
                "required": [
                    "bpm",
                    "target_duration_seconds",
                    "sections"
                ]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "lookup_reference_track",
            "description": (
                "Look up factual metadata about an existing released song using "
                "MusicBrainz. Use this when a musician or producer names a real "
                "reference track and its duration, release information, or identity "
                "is needed for production planning. Always use this tool instead of "
                "guessing the duration of a reference track. If both title and artist "
                "are known, provide both to reduce ambiguity."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "track_name": {
                        "type": "string",
                        "description": (
                            "Title of the released reference track, "
                            "for example 'Nights'."
                        ),
                    },
                    "artist": {
                        "type": "string",
                        "description": (
                            "Optional artist name used to disambiguate the track, "
                            "for example 'Frank Ocean'."
                        ),
                    },
                },
                "required": ["track_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "analyze_audio_track",
            "description": (
                "Analyze an audio file uploaded by the user and return objective "
                "music/audio features including estimated tempo, estimated key, "
                "signal dynamics, spectral brightness, onset activity, an energy "
                "profile over time, and candidate structural-change points. "
                "Use this whenever the user asks you to inspect, diagnose, compare, "
                "or reason about the actual sound of their uploaded track, demo, "
                "loop, bounce, or sample. "
                "The estimates are analytical measurements, not ground truth. "
                "If the user provides timestamps for a specific section, pass them "
                "as start_seconds and end_seconds. "
                "Colon-formatted timestamps are MM:SS unless context clearly "
                "indicates otherwise: 0:45 = 45 seconds, 1:10 = 70 seconds, "
                "10:00 = 600 seconds, 10:30 = 630 seconds. "
                "If the user refers to their selected region in Track View and the "
                "workspace context gives selected timestamps, pass those exact values. "
                "If the tool reports that a requested range is beyond the track, "
                "report that to the user; never re-run it with a different range "
                "in its place. "
                "Results contain raw measurements plus producer_summary, a "
                "deterministic, conservative interpretation computed from them "
                "(level, rhythmic activity, and brightness relative to explicit "
                "baselines, notable_observations, and detected candidate "
                "transitions). Base producer-facing explanations on "
                "producer_summary without changing its direction or magnitude; use "
                "the raw fields when the user asks for technical detail. Treat "
                "interpretation_notes and producer_summary.limitations as binding "
                "caveats."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "audio_file_id": {
                        "type": "string",
                        "description": (
                            "The exact uploaded audio file ID provided in the "
                            "conversation attachment context."
                        ),
                    },
                    "start_seconds": {
                        "type": "number",
                        "description": (
                            "Optional start time in seconds if the user wants "
                            "analysis of only part of the track."
                        ),
                    },
                    "end_seconds": {
                        "type": "number",
                        "description": (
                            "Optional end time in seconds if the user wants "
                            "analysis of only part of the track."
                        ),
                    },
                },
                "required": [
                    "audio_file_id"
                ],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "focus_audio_region",
            "description": (
                "Visually highlight a timestamped region of the user's uploaded "
                "track in the Studio Copilot Track View (waveform/spectrogram). "
                "This is a UI action that directs the user's attention; it does "
                "NOT measure or analyze audio. Use it when the user asks you to "
                "show, highlight, locate, point out, or focus on a specific part "
                "of the track, or when directing visual attention to an exact "
                "region you identified from analyze_audio_track results would "
                "materially improve your explanation. Base the range on tool "
                "measurements or user-provided timestamps, not guesses. Do not "
                "call it on every response. Use a short neutral label (e.g. "
                "'Energy dip', 'Selected region'); do not label regions as verse, "
                "chorus, drop, etc. unless the user identified them that way."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "audio_file_id": {
                        "type": "string",
                        "description": (
                            "The exact uploaded audio file ID provided in the "
                            "conversation attachment context."
                        ),
                    },
                    "start_seconds": {
                        "type": "number",
                        "description": (
                            "Region start in seconds. Convert MM:SS first, "
                            "e.g. 1:07 -> 67."
                        ),
                    },
                    "end_seconds": {
                        "type": "number",
                        "description": (
                            "Region end in seconds. Must be greater than "
                            "start_seconds and within the track."
                        ),
                    },
                    "label": {
                        "type": "string",
                        "description": (
                            "Short neutral label shown on the highlight, "
                            "at most a few words, e.g. 'Energy dip'."
                        ),
                    },
                    "reason": {
                        "type": "string",
                        "description": (
                            "One plain-language sentence explaining why this "
                            "region matters, grounded in measurements, e.g. "
                            "'Sits about 5 dB lower in level than the rest of "
                            "the track.'"
                        ),
                    },
                },
                "required": [
                    "audio_file_id",
                    "start_seconds",
                    "end_seconds",
                    "label",
                    "reason",
                ],
            },
        },
    },
    UPDATE_PROJECT_STATE_TOOL,
]


# What the harness actually runs.
TOOL_MAP = {"transform_sample": transform_sample, "build_arrangement": build_arrangement,"lookup_reference_track": lookup_reference_track,"analyze_audio_track": analyze_audio_track,"focus_audio_region": focus_audio_region,"update_project_state": update_project_state,}

# Tools that act on the current session. The harness supplies the session's
# project state and attached audio_file_id; the model never sees session IDs.
CONTEXT_TOOLS = {"update_project_state"}


def run_tool(name: str, args: dict, context: dict | None = None) -> str:
    """Run one tool call without allowing bad model arguments to crash the agent loop."""
    if name not in TOOL_MAP:
        return json.dumps({"error": f"Unknown tool '{name}'. Available: {list(TOOL_MAP)}"})
    if not isinstance(args, dict):
        return json.dumps({"error": f"Arguments for {name} must be a JSON object."})
    try:
        if name in CONTEXT_TOOLS:
            if not context or "project_state" not in context:
                return json.dumps({"error": f"{name} requires an active chat session."})
            if name == "update_project_state" and "turn" in context:
                return guarded_update_project_state(
                    context["project_state"],
                    context.get("audio_file_id"),
                    context["turn"],
                    **args,
                )
            return TOOL_MAP[name](
                context["project_state"],
                context.get("audio_file_id"),
                **args,
            )
        return TOOL_MAP[name](**args)
    except TypeError as e:
        parameters = next(
            (list(tool["function"]["parameters"].get("properties", {})) for tool in TOOLS if tool["function"]["name"] == name),
            [],
        )
        return json.dumps({
            "error": f"Bad arguments for {name}: {e}",
            "action": (
                f"Call {name} again with only these top-level arguments: "
                f"{', '.join(parameters)}. Do not nest them under another key."
            ),
        })
    except Exception as e:
        return json.dumps({"error": f"{name} failed unexpectedly: {type(e).__name__}: {e}"})
